spring.application.name=EPIAssist-v2
spring.datasource.url=jdbc:postgresql://localhost:5432/epiassist_db
spring.datasource.username=postgres
spring.datasource.password=cosmonet
spring.jpa.hibernate.ddl-auto=update
server.port=8081
